### ISSUE TITLE
AtrributeError

### ISSUE THREAD

**Issue by Murraytl** [fireeye/iocs#2]
AttributeError: 'StringObjectPropertyType' object has no attribute 'startswith' when running python openioc_to_stix.py (APT3 db0b6ac6-874a-498e-892b-ac7c2020e061.ioc)

**Comment by williamgibb** [comment]
It may be more appropriate to post this error, with a complete traceback & a link to the source IOC, too the OpenIOC to Stix project hosted by MITRE at https://github.com/STIXProject/openioc-to-stix

**Comment by williamgibb** [comment]
No further comment from reporter, and related to a third-party tool.  Closing issue.
