### ISSUE TITLE
False positive in IronGate IOCs

### ISSUE THREAD

**Issue by bartblaze** [fireeye/iocs#7]
File with hash 7a0c1017e6b5bb5dc776b3b883a1d0e0 in the [IronGate IOCs](https://github.com/fireeye/iocs/blob/master/BlogPosts/9cee306d-5441-4cd3-932d-f3119752634c.ioc) seems to be the legitimate [NetResView](http://www.nirsoft.net/utils/netresview.html). 

Please verify.

_Edit:_ while it's technically not wrong, I don't think it needs to be included as an IOC. Cheers.

**Comment by williamgibb** [comment]
That is correct.  The hash is logically AND'd with a filename term.

**Comment by bartblaze** [comment]
Hi William,

Thanks for your reply. That makes sense.

Cheers!
